define([
  './home/HomePage',
  './select-coinslot/SelectCoinslotPage.js',
  './buy-eload/BuyEloadPage.js',
  './phone-number-form/PhoneNumberPage.js',
  './eload-products/EloadProductsPage.js',
  './regular-load-form/RegularLoadPage.js',
  './eload-paying/EloadPayingPage.js',
]);
